# Site settings
title: "Florian Hartmann"
email:
description: > # this means to ignore newlines until "baseurl:"
#baseurl: "/beta/" # the subpath of your site, e.g. /blog/
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://david9se.github.io/florian.github.io/" # the base hostname & protocol for your site
github_username: david9se

# Build settings
markdown: kramdown
permalink: ":title/"
highlighter: rouge
plugins: [jekyll-paginate]

# Pagination
paginate: 100
paginate_path: "blog/page/:num/"

# Minification
sass:
  style: compressed
