# Site settings
title: "Florian Hartmann"
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://florian.github.io/" # the base hostname & protocol for your site
github_username: florian

# Build settings
markdown: kramdown
permalink: ":title/"
highlighter: pygments
plugins: [jekyll-paginate]

# Pagination
paginate: 10
paginate_path: "blog/page/:num/"

# Minification
sass:
  style: compressed
